// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr7x9msJ32UUc1bMHYrXDPOGllDwwYKEk',
    appId: '1:139668820722:web:e8ad6350a60757ba0c366b',
    messagingSenderId: '139668820722',
    projectId: 'ideiacode-cadastro',
    authDomain: 'ideiacode-cadastro.firebaseapp.com',
    storageBucket: 'ideiacode-cadastro.appspot.com',
    measurementId: 'G-VSSY70EVBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsIOG4nmVqC9uTGjdETi4HOc3o4n66UN0',
    appId: '1:139668820722:android:8a6f3ddab564e9c70c366b',
    messagingSenderId: '139668820722',
    projectId: 'ideiacode-cadastro',
    storageBucket: 'ideiacode-cadastro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjfaWxQkr6-m5G4Y_R1x_xqIb5KBa6_5s',
    appId: '1:139668820722:ios:64a96ae7022e72e40c366b',
    messagingSenderId: '139668820722',
    projectId: 'ideiacode-cadastro',
    storageBucket: 'ideiacode-cadastro.appspot.com',
    iosBundleId: 'br.com.ideiacode.ideiacodeCadastro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjfaWxQkr6-m5G4Y_R1x_xqIb5KBa6_5s',
    appId: '1:139668820722:ios:64a96ae7022e72e40c366b',
    messagingSenderId: '139668820722',
    projectId: 'ideiacode-cadastro',
    storageBucket: 'ideiacode-cadastro.appspot.com',
    iosBundleId: 'br.com.ideiacode.ideiacodeCadastro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr7x9msJ32UUc1bMHYrXDPOGllDwwYKEk',
    appId: '1:139668820722:web:fe6aed8dcc3726a00c366b',
    messagingSenderId: '139668820722',
    projectId: 'ideiacode-cadastro',
    authDomain: 'ideiacode-cadastro.firebaseapp.com',
    storageBucket: 'ideiacode-cadastro.appspot.com',
    measurementId: 'G-GPZKCQQHZ9',
  );
  
}
