name: ideiacode_cadastro
description: "Projeto de cadastro de clientes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1 #Note: You mentioned downgrading to a compatible version)
  cloud_firestore: ^5.0.1
  provider: ^6.1.2
  intl: ^0.19.0
  mask_text_input_formatter: ^2.1.0
  shared_preferences: ^2.0.11
  image_picker: any #(Add this dependency if needed)
  flutter_plugin_android_lifecycle: ^2.0.0
  email_validator: ^3.0.0
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
