name: ideiacode_cadastro
description: "Projeto de cadastro de clientes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^2.0.11
  provider: ^6.1.2
  mask_text_input_formatter: ^2.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0  # Downgrade para versão compatível
  cloud_firestore: ^5.0.1
  image_picker: any  # Adicione esta dependência se for necessária
  flutter_plugin_android_lifecycle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
